routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);
Route::group(['middleware' => ['web', 'auth']], function () {
    Route::get('password/change', 'UserController@showChangePasswordForm')->name('password.change');
    Route::POST('password/change', 'UserController@changePassword');
    Route::get('user/profile', 'UserController@showProfile')->name('user.profile');
    Route::patch('user/profile/{user}', 'UserController@profile')->name('user.profile.update');
    Route::post('user/profile/address', 'UserController@address')->name('user.profile.address');
    Route::patch('user/profile/{address}/address', 'UserController@addressupdate')->name('user.profile.addressupdate');

    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('customer/import', 'CustomerController@showCustomerImportForm')->name('customer.import');
    Route::post('customer/import', 'CustomerController@importCustomer');
    Route::get('customer/{customer}/print', 'CustomerController@print')->name('customer.print');
    Route::resource('customer', 'CustomerController');
});

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Model\Customer;
use Illuminate\Http\Request;
use App\DataTables\CustomerDataTable;
use Svg\Tag\Rect;
use Yajra\DataTables\Contracts\DataTable;
use Yajra\DataTables\Facades\DataTables;

use function Ramsey\Uuid\v1;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datatable = Customer::latest()->get();
        return view('customer.index', compact('datatable'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Customer::create($this->validateRequest($request));
        return redirect(route('customer.index'))->with('success', 'Customer added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Customer $customer)
    {
        return view('customer.show', compact('customer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Customer $customer)
    {
        return view('customer.edit', compact('customer'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customer $customer)
    {
        $customer->update($this->validateRequest($request));
        return redirect(route('customer.index'))->with('success', 'Customer updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customer $customer)
    {
        $customer->delete();
        return redirect(route('customer.index'))->with('success', 'Customer removed successfully');
    }

    public function print(Customer $customer)
    {
        $userAddress = auth()->user()->user_addresses()->first();
        return view('customer.print', compact('customer', 'userAddress'));
    }

    public function showCustomerImportForm()
    {
        return view('customer.import');
    }

    public function importCustomer(Request $request)
    {
        $request->validate([
            'importFile' => 'required|mimes:xlsx|size:5000',
        ]);
        dd($request);
    }
    
    public function validateRequest($request)
    {
        return $request->validate([
            'customername' => 'required',
            'addressline1' => 'required',
            'addressline2' => '',
            'addressline3' => '',
            'pincode' => 'required|numeric',
            'number' => 'required',
        ]);
    }
}

resources/views/customer/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
<h1>Add Customers</h1>
@stop
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
          <li class="nav-item">
            <a class="nav-link" href="{!! route('customer.index') !!}"><i class="fa fa-list mr-2"></i>Customers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-plus mr-2"></i>Add Customers</a>
          </li>
          <div class="ml-auto d-inline-flex">
            <li class="nav-item">
              <a class="nav-link pt-1" id="import" href="{{route('customer.import')}}" ><i class="fas fa-file-import"></i> {{__('Import')}}</a>
            </li>
          </div>
        </ul>
      </div>
      <div class="card-body table-responsive">
        <div class="clearfix"></div>
        <form action="{{route('customer.store')}}" method="post">
            @csrf
            <div class="form-group">
              <label for="customername">Customer Name</label>
              <input type="text" name="customername" id="customername" class="form-control @error('customername') is-invalid @enderror" placeholder="Please enter the name of your customer." value="{{old('customername')}}">
              @error('customername')
                <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                </div>
              @enderror
            </div>
            <div class="form-group">
                <label for="number">Customer Number</label>
                <input type="tel" name="number" id="number" class="form-control @error('number') is-invalid @enderror" placeholder="Please enter the number of your customer." value="{{old('number')}}">
                @error('number')
                <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                </div>
                @enderror
              </div>
              <div class="form-group">
                <label for="addressline1">Customer Address</label>
                <input type="text" name="addressline1" id="addressline1" class="form-control @error('addressline1') is-invalid @enderror" placeholder="Locality / House no ,of your cusotmer." value="{{old('addressline1')}}">
                @error('addressline1')
                <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                </div>
                @enderror
              </div>
              <div class="form-group">
                <input type="text" name="addressline2" id="addressline2" class="form-control @error('addressline2') is-invalid @enderror" placeholder="Town / City, of your cusotmer." value="{{old('addressline2')}}">
                @error('addressline2')
                <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                </div>
                @enderror
              </div>
              <div class="form-group">
                <input type="text" name="addressline3" id="addressline3" class="form-control @error('addressline3') is-invalid @enderror" placeholder="State of your customer." value="{{old('addressline3')}}">
                @error('addressline3')
                <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                </div>
                @enderror
              </div>
              <div class="form-group">
                <label for="pincode">Customer Pincode</label>
                <input type="tel" name="pincode" id="pincode" class="form-control @error('pincode') is-invalid @enderror" placeholder="Please enter the pincode of your customer." value="{{old('pincode')}}">
                @error('pincode')
                <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                </div>
                @enderror
              </div>
              <button class="btn-primary btn btn-lg w-100">Submit</button>
        </form>
      </div>
  </div>
  </div>
</div>
@stop

@section('css') @stop
@section('js') @stop

resources/views/customer/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
<h1>Edit {{$customer->customername}}'s Details</h1>
@stop
@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
            <li class="nav-item">
              <a class="nav-link" href="{!! route('customer.index') !!}"><i class="fa fa-list mr-2"></i>Customers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-plus mr-2"></i>Add Customers</a>
            </li>
          </ul>
        </div>
        <div class="card-body table-responsive">
          <div class="clearfix"></div>
          <form action="{{route('customer.update',$customer->id)}}" method="post">
            @csrf @method('patch')
              <div class="form-group">
                <label for="customername">Customer Name</label>
                <input type="text" name="customername" id="customername" class="form-control @error('customername') is-invalid @enderror" placeholder="Please enter the name of your customer." value="{{old('customername')??$customer->customername}}">
                @error('customername')
                  <div class="invalid-feedback">
                      <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>
              <div class="form-group">
                  <label for="number">Customer Number</label>
                  <input type="tel" name="number" id="number" class="form-control @error('number') is-invalid @enderror" placeholder="Please enter the number of your customer." value="{{old('number')??$customer->number}}">
                  @error('number')
                  <div class="invalid-feedback">
                      <strong>{{ $message }}</strong>
                  </div>
                  @enderror
                </div>
                <div class="form-group">
                  <label for="addressline1">Customer Address</label>
                  <input type="text" name="addressline1" id="addressline1" class="form-control @error('addressline1') is-invalid @enderror" placeholder="Locality / House no ,of your cusotmer." value="{{old('addressline1')??$customer->addressline1}}">
                  @error('addressline1')
                  <div class="invalid-feedback">
                      <strong>{{ $message }}</strong>
                  </div>
                  @enderror
                </div>
                <div class="form-group">
                  <input type="text" name="addressline2" id="addressline2" class="form-control @error('addressline2') is-invalid @enderror" placeholder="Town / City, of your cusotmer." value="{{old('addressline2')??$customer->addressline2}}">
                  @error('addressline2')
                  <div class="invalid-feedback">
                      <strong>{{ $message }}</strong>
                  </div>
                  @enderror
                </div>
                <div class="form-group">
                  <input type="text" name="addressline3" id="addressline3" class="form-control @error('addressline3') is-invalid @enderror" placeholder="State of your customer." value="{{old('addressline3')??$customer->addressline3}}">
                  @error('addressline3')
                  <div class="invalid-feedback">
                      <strong>{{ $message }}</strong>
                  </div>
                  @enderror
                </div>
                <div class="form-group">
                    <label for="pincode">Customer Pincode</label>
                    <input type="tel" name="pincode" id="pincode" class="form-control @error('pincode') is-invalid @enderror" placeholder="Please enter the pincode of your customer." value="{{old('pincode')??$customer->pincode}}">
                    @error('pincode')
                    <div class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </div>
                    @enderror
                  </div>
                <button class="btn-primary btn btn-lg w-100">Submit</button>
          </form>
        </div>
    </div>
    </div>
  </div>
@stop

@section('css') @stop

@section('js') @stop

resources/views/customer/import.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
<h1>Import Customers</h1>
@stop
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
                  <li class="nav-item">
                    <a class="nav-link" href="{!! url()->current() !!}"><i class="fa fa-list mr-2"></i>Customers</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{!! route('customer.create') !!}"><i class="fa fa-plus mr-2"></i>Add Customers</a>
                  </li>
                  @include('layouts.right_toolbar')
                </ul>
              </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                      <label>Choose file to import</label>
                      <div class="custom-file">
                        <input type="file" name="importFile" class="custom-file-input @error('importFile') is-invalid @enderror" id="customFile" aria-describedby="helpId" accept=".xlsx">
                        <small id="helpId" class="text-muted">Only use XLSX format</small>
                        @error('importFile')
                          <div class="invalid-feedback">
                              <strong>{{ $message }}</strong>
                          </div>
                         @enderror
                        <label class="custom-file-label" for="customFile">Choose file</label>
                      </div>
                    </div>

                    <button class="btn btn-primary btn-lg w-100">Import</button>
                </form>
            </div>
        </div>
    </div>
</div>
@stop

@section('css') @stop

@section('js') @stop

resources/views/customer/index.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
<h1>Home</h1>
@stop
@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
          <li class="nav-item">
            <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-list mr-2"></i>Customers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{!! route('customer.create') !!}"><i class="fa fa-plus mr-2"></i>Add Customers</a>
          </li>
          @include('layouts.right_toolbar', compact('datatable'))
        </ul>
      </div>
      <div class="card-body table-responsive">
        @include('customer.table')
        <div class="clearfix"></div>
      </div>
  </div>
  </div>
</div>
@stop

@section('css') @stop

resources/views/customer/print.blade.php
<html>
<head>
	<title>PrintOut</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" />
</head>
<style> td,tr{
	text-align: center;
	margin: 0!important;
	padding: 0!important;
}
th{
	font-weight: 1000;
}
.fs-75{
	font-size: 30px;
}
	@media print{
		@page {size: landscape}
		.border-bottom{
			border: none!important;
		}
		.row
		{
          transform: scale(1.05);
          margin-top: 1rem;/*
          margin-left: 3rem;
          margin-right: -5rem;*/
		}
		.fs-75 td span{
			font-size: 35px;
		}
		td{
			/*height: 5rem;*/
			/*vertical-align: middle!important;*/
		}
		.mt-5 td span{
			font-size: 25px!important;
		}
		.mt-5{
			margin-top: 6rem!important;
		}
		th{
			font-family: sans-serif;
			text-decoration: underline;
			font-size: 45px!important;
		}
		.parcel-number{
			text-transform: uppercase;
			position: absolute;
			bottom: 7rem;
			left: -7rem;
			transform: rotate(-90deg)
		}
	}
</style>
@if(!isset($userAddress) && empty($userAddress) )
	<script>
		alert('Please add your address details first.');
		location.replace('{{route("home")}}');
	</script>
@endif
<body onafterprint="myFunction()">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<table class="mb-0  table fs-75">
					<thead>
						<tr>
							<th colspan="3" class="border-0 text-center font-size">
								<span class="border-bottom">TO</span>
							</th>
						</tr>
					</thead>
					<tbody class="text-justify ">
						<tr>
							<td class="border-0">
								<span class="font-weight-bold">{{$customer->customername}}</span>
							</td>
						</tr>
						<tr>

							<td class="border-0"> 
								<span class="font-weight-bold">
									{{$customer->addressline1}}
								</span><br>
								<span class="font-weight-bold">
									{{$customer->addressline2}}
								</span><br>
								<span class="font-weight-bold">
									{{$customer->addressline3}}
								</span>
							</td>
						</tr>
							<td class="border-0">
								<span class="font-weight-bold">
								<i class="fas fa-mobile"></i>
								{{$customer->number}}</span>
							</td>
						</tr>
						<tr>
							<td class="border-0">
								<span class="font-weight-bold" style="margin-left: -2rem">
								<i class="fas fa-map-pin"></i>
								@empty(!$customer->pincode)
									{{$customer->pincode}}
								@else
									{{__('N|A')}}
								@endempty
								</span>
							</td>
						</tr>
					</tbody>
				</table>
				<table class="mb-0 table mt-5">
					<thead>
						<tr>
							<th colspan="3" class="border-0 text-center font-size">
								<span class="border-bottom">From</span>
							</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class="border-0">
								<span class="font-weight-bold">{{$userAddress->user->name}}</span>
							</td>
						</tr>
						<tr>
							<td class="border-0"> 
								<span class="font-weight-bold">
									{{$userAddress->addressline1}},{{$userAddress->addressline2}}<br>{{$userAddress->addressline3}}
								</span>
							</td>
						</tr>
						<tr>
							<td class="border-0">
								<span class="font-weight-bold">
								<i class="fas fa-mobile"></i>
								{{$userAddress->pincode}}</span>
							</td>
						</tr>
						<tr>
							<td class="border-0">
								<span class="font-weight-bold" style="margin-left: -2rem">
								<i class="fas fa-map-pin"></i>
								{{$userAddress->number}}</span>
							</td>
						</tr>
					</tbody>
				</table>
			</div>
			<div class="col-4">
				<h2 class="parcel-number">Parcel number - <span id="parcel"></span></h2>
			</div>
		</div>
	</div>	
	<script>
		function myFunction(params) {
			setTimeout(function(){
				window.close();
			}, 500);
		}
		let parcelnumber = prompt('Please enter parcel number.');
		if (typeof parcelnumber == 'string') {
			if(parcelnumber.length){
				$('#parcel').html(parcelnumber);
				window.print();
			}else{
				alert('You can\'t continue without entering a number.')
				location.reload();
			}
		}else{
			alert('You can\'t continue without entering a number.')
			location.reload();
		}
	</script>
</body>
</html>

resources/views/customer/show.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
<h1>{{$customer->customername}}'s Details</h1>
@stop
@section('content')
<div class="row">
    <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
            <li class="nav-item">
              <a class="nav-link" href="{!! route('customer.index') !!}"><i class="fa fa-list mr-2"></i>Customers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{!! route('customer.create') !!}"><i class="fa fa-plus mr-2"></i>Add Customers</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-info mr-2"></i>{{$customer->customername}}'s Details</a>
            </li>
            @include('layouts.right_toolbar',compact('customer'))
          </ul>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-1 col-2 font-weight-bold">Name :</div>
                <div class="col-md-11">{{$customer->customername}}</div>
            </div>
            <div class="row">
                <div class="col-lg-1 col-2 font-weight-bold">Number :</div>
                <div class="col-md-11">{{$customer->number}}</div>
            </div>
            <div class="row">
                <div class="col-lg-1 col-2 font-weight-bold">Address :</div>
                <div class="col-md-11">
                    <div class="row">
                        <div class="col-md-12">
                            <span class="d-block">{{$customer->addressline1}}</span>
                            <span class="d-block">{{$customer->addressline1}}</span>
                            <span class="d-block">{{$customer->addressline1}}</span>
                        </div>
                    </div>
                </div>
            </div>
          <div class="d-flex">
            <a href="{{route('customer.edit',$customer->id)}}" class="px-2 text-warning"><i class="fas fa-pencil-alt    "></i></a>
            <a href="#"
                onclick="event.preventDefault(); return confirm('Are you sure? This action is irreversible.'); document.getElementById('{{$customer->id}}delete').submit();"
                class="px-2 text-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>
            <form action="{{route('customer.destroy',$customer->id)}}" method="post"
                class="d-none" id="{{$customer->id}}delete">@csrf @method('delete')</form>
          </div>
          <div class="clearfix"></div>
        </div>
    </div>
    </div>
  </div>
@stop

@section('css') @stop

@section('js') @stop

resources/views/customer/table.blade.php
<table class="table text-center" id="table">
    <thead>
        <tr>
            <th style="width: 2%">#</th>
            <th class="w-25">Customer Name</th>
            <th>Customer Number</th>
            <th>Customer Address</th>
            <th>Pincode</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($datatable as $key => $item)
            <tr>
                <td style="width: 2%">{{$key+1}}</td>
                <td class="w-25">{{$item->customername}}</td>
                <td>{{$item->number}}</td>
                <td><address>{!! $item->addressline1 .'<br>'.$item->addressline2.'<br>'.$item->addressline3!!}</address></td>
                <td>{{$item->pincode}}</td>
                <td>
                    <a href="{{route('customer.show',$item->id)}}" class="px-2 text-info"><i class="fa fa-eye" aria-hidden="true"></i></a>
                    <a href="{{route('customer.edit',$item->id)}}" class="px-2 text-warning"><i class="fas fa-pencil-alt    "></i></a>
                    <a href="#"
                        onclick="event.preventDefault(); document.getElementById('{{$item->id}}delete').submit();"
                        class="px-2 text-danger"><i class="fa fa-trash" aria-hidden="true"></i></a>
                    <form action="{{route('customer.destroy',$item->id)}}" method="post"
                        class="d-none" id="{{$item->id}}delete">@csrf @method('delete')</form>
                </td>
            </tr>
        @endforeach
    </tbody>
</table>